Models/ErrorViewModel.cs
using System;

namespace StudentModel.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/IStudentRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentModel.Models
{
    
    public interface IStudentRepository
    {
        //Inserting a student to database.
        public bool Insert(Student s);

    }
}

Models/Student.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace StudentModel.Models
{
    //Student model.
    public class Student
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int Id { get; set; }

        public string Name { get; set; }

        
        public int Class { get; set; }

        
        public int Roll { get; set; }

        
        public string School { get; set; }

        
        public string Gender { get; set; }



    }
}

Models/StudentContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentModel.Models
{

    public class StudentContext:DbContext
    {
        public StudentContext(DbContextOptions options):base(options)
        {

        }

        public DbSet<Student> Students { get; set; }
    }
}

Models/StudentRepository.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentModel.Models
{
    //Implementing repository pattern.
    public class StudentRepository:IStudentRepository
    {
        private StudentContext context;

        public StudentRepository(StudentContext context)
        {
            
            this.context = context;
        }


        
        public bool Insert(Student s)
        {
            var query = from st in context.Students
                        where st.Name == s.Name
                        && st.Roll == s.Roll
                        select st;

            
            if (query.Count() >= 1)
                return false;
            else
            {
                
                context.Students.Add(s);
                context.SaveChanges();
                return true;
            }
        }
    }
}

Controllers/HomeController.cs
using StudentModel.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace StudentModel.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/StudController.cs
using StudentModel.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace StudentModel.Controllers
{
    public class StudController : Controller
    {
        
        private readonly IStudentRepository obj;

        public StudController(IStudentRepository student)
        {
            obj = student;
        }
        
        //Action to get details.
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        //Action to save data into database.
        [HttpPost]
        public IActionResult Add(Student student)
        {
            bool result = obj.Insert(student);
            if (result == true)
                ViewBag.Message = "Student Added Successfully";
            else
                ViewBag.Message = "Failed to Add Student Details";
            return View();
        }


        
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - StudentModel</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">My Project</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Stud" asp-action="Add">Add</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - StudentModel 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Stud/Add.cshtml
@model StudentModel.Models.Student

@{
    ViewBag.Title = "Add";
}

<h2>Add New Student</h2>
<div class="row" style="margin-left:0px;">
    
    @using (Html.BeginForm("Add", "Stud"))
    {
        <div class="form-group">
            @Html.Label("Name")  @Html.TextBoxFor(s => s.Name, new { @class = "form-control" })

        </div>


        <div class="form-group">
            @Html.Label("Class") @Html.TextBoxFor(s => s.Class, new { @class = "form-control", @type = "number" })

        </div>

        <div class="form-group">
            @Html.Label("Roll No") @Html.TextBoxFor(s => s.Roll, new { @class = "form-control", @type = "number" })

        </div>

        <div class="form-group">
            @Html.Label("School")  @Html.TextBoxFor(s => s.School, new { @class = "form-control" })

        </div>

        <div class="form-group">

            @Html.Label("Gender")  @Html.TextBoxFor(s => s.Gender, new { @class = "form-control" })

        </div>

        <button type="submit" class="btn btn-info" id="btnSubmit">Save</button>

    }
</div>

@if (ViewBag.Message != "")
{
    <h4 id="Message">@ViewBag.Message</h4>
}